# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RCPPSampleFromRIM <- function(numSamplesVec, rimNodesMat) {
    .Call('_RIM_RCPPSampleFromRIM', PACKAGE = 'RIM', numSamplesVec, rimNodesMat)
}

RCPPAverageDiscMatrix <- function(samples) {
    .Call('_RIM_RCPPAverageDiscMatrix', PACKAGE = 'RIM', samples)
}

RCPPStructByDP <- function(aveDiscMatrix, refRanking, makeCanonical) {
    .Call('_RIM_RCPPStructByDP', PACKAGE = 'RIM', aveDiscMatrix, refRanking, makeCanonical)
}

RCPPSASearch <- function(aveDiscMatrix, refRanking, inverseTemp, maxIter, makeCanonical, verbose) {
    .Call('_RIM_RCPPSASearch', PACKAGE = 'RIM', aveDiscMatrix, refRanking, inverseTemp, maxIter, makeCanonical, verbose)
}

RCPPLogProbRIM <- function(rimNodesMat, aveDiscMatrix) {
    .Call('_RIM_RCPPLogProbRIM', PACKAGE = 'RIM', rimNodesMat, aveDiscMatrix)
}

RCPPthetaMLERIM <- function(rimNodesMat, aveDiscMatrix) {
    .Call('_RIM_RCPPthetaMLERIM', PACKAGE = 'RIM', rimNodesMat, aveDiscMatrix)
}

