# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RCPPSampleFromRIM <- function(numSamplesVec, rimNodesList) {
    .Call('RIM_RCPPSampleFromRIM', PACKAGE = 'RIM', numSamplesVec, rimNodesList)
}

RCPPAverageDiscMatrix <- function(samples) {
    .Call('RIM_RCPPAverageDiscMatrix', PACKAGE = 'RIM', samples)
}

RCPPStructByDP <- function(aveDiscMatrix, refRanking, makeCanonical) {
    .Call('RIM_RCPPStructByDP', PACKAGE = 'RIM', aveDiscMatrix, refRanking, makeCanonical)
}

RCPPSASearch <- function(aveDiscMatrix, refRanking, inverseTemp, maxIter, makeCanonical, verbose) {
    .Call('RIM_RCPPSASearch', PACKAGE = 'RIM', aveDiscMatrix, refRanking, inverseTemp, maxIter, makeCanonical, verbose)
}

RCPPLogProbRIM <- function(rimNodesList, aveDiscMatrix) {
    .Call('RIM_RCPPLogProbRIM', PACKAGE = 'RIM', rimNodesList, aveDiscMatrix)
}

RCPPthetaMLERIM <- function(rimNodesList, aveDiscMatrix) {
    .Call('RIM_RCPPthetaMLERIM', PACKAGE = 'RIM', rimNodesList, aveDiscMatrix)
}

